"""something

Revision ID: 3c8fa94f21e0
Revises: 7a1b25349ddb
Create Date: 2023-10-03 18:20:40.635234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8fa94f21e0'
down_revision = '7a1b25349ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('e_mail', sa.String(length=145), nullable=True))
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=145), nullable=True))
        batch_op.drop_column('e_mail')

    # ### end Alembic commands ###
