"""removed external model

Revision ID: 4af2712368e2
Revises: 543c31f8f5a2
Create Date: 2023-10-03 17:28:45.695090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af2712368e2'
down_revision = '543c31f8f5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('external')

    op.create_table('external_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=150), nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), nullable=True),
    sa.Column('username', sa.VARCHAR(length=150), nullable=True),
    sa.Column('name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('bio', sa.VARCHAR(length=500), nullable=True),
    sa.Column('location', sa.VARCHAR(length=150), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
