"""projects added

Revision ID: 560cbaa52eba
Revises: 96cfd25c0908
Create Date: 2023-10-07 18:25:23.823074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560cbaa52eba'
down_revision = '96cfd25c0908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skilles', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('skilles')

    # ### end Alembic commands ###
