"""profile pic

Revision ID: 96cfd25c0908
Revises: 9bc27bd7024f
Create Date: 2023-10-06 18:11:55.021150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96cfd25c0908'
down_revision = '9bc27bd7024f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.BLOB(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.String(length=100),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
