"""topic edited

Revision ID: b0ae4c303cc1
Revises: 91fe5d8bbbfa
Create Date: 2023-10-05 23:58:00.947439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ae4c303cc1'
down_revision = '91fe5d8bbbfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=50), nullable=True))
        batch_op.drop_column('text_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
