"""user_interesets was added

Revision ID: ccd4debfa2c4
Revises: 560cbaa52eba
Create Date: 2023-10-07 18:47:08.414045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd4debfa2c4'
down_revision = '560cbaa52eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_interestes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_interestes')

    # ### end Alembic commands ###
