"""added external id

Revision ID: e4d0ceb4ba8b
Revises: 4af2712368e2
Create Date: 2023-10-03 17:41:56.054875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e4d0ceb4ba8b"
down_revision = "4af2712368e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("external_id", sa.String(length=150), nullable=True)
        )
        batch_op.create_unique_constraint("external_id", ["external_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
